osx_image: xcode7.3
language: objective-c
install:
    - gem install cocoapods -v 1.0.1 --no-document

before_script:
    - cd Example
    - pod repo update --silent
    - pod install

xcode_workspace: LiquidFloatingActionButton.xcworkspace
xcode_scheme: LiquidFloatingActionButton-Example
xcode_sdk: iphonesimulator9.3
